"""added password column to farmers table

Revision ID: 716d8e34cd26
Revises: feb5f8cbc621
Create Date: 2024-11-20 12:50:50.613392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716d8e34cd26'
down_revision = 'feb5f8cbc621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
